"""Add user preferences columns

Revision ID: 3af3e0e52a29
Revises: 
Create Date: 2025-03-26 14:27:02.177804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af3e0e52a29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_cuisines', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('budget_preference', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('budget_preference')
        batch_op.drop_column('preferred_cuisines')

    # ### end Alembic commands ###
